#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BollerTuneZ.Resource", IsApplication=true)]

namespace BollerTuneZ
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::BTZ.App.Communication.Resource.String.ApplicationName = global::BollerTuneZ.Resource.String.ApplicationName;
			global::BTZ.App.Communication.Resource.String.Hello = global::BollerTuneZ.Resource.String.Hello;
			global::BTZ.App.Communication.Resource.String.library_name = global::BollerTuneZ.Resource.String.library_name;
			global::BTZ.App.Data.Resource.String.ApplicationName = global::BollerTuneZ.Resource.String.ApplicationName;
			global::BTZ.App.Data.Resource.String.Hello = global::BollerTuneZ.Resource.String.Hello;
			global::BTZ.App.Data.Resource.String.library_name = global::BollerTuneZ.Resource.String.library_name;
			global::BTZ.App.DataAccess.Resource.String.ApplicationName = global::BollerTuneZ.Resource.String.ApplicationName;
			global::BTZ.App.DataAccess.Resource.String.Hello = global::BollerTuneZ.Resource.String.Hello;
			global::BTZ.App.DataAccess.Resource.String.library_name = global::BollerTuneZ.Resource.String.library_name;
			global::BTZ.App.Infrastructure.Resource.String.ApplicationName = global::BollerTuneZ.Resource.String.ApplicationName;
			global::BTZ.App.Infrastructure.Resource.String.Hello = global::BollerTuneZ.Resource.String.Hello;
			global::BTZ.App.Infrastructure.Resource.String.library_name = global::BollerTuneZ.Resource.String.library_name;
			global::SQLite.Resource.String.ApplicationName = global::BollerTuneZ.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::BollerTuneZ.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int myButton = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int test_btn_reg = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int test_lbn_status = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActivtyTest = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int app_name = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int hello = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
